### ISSUE TITLE
change timer

### ISSUE THREAD

**Issue by dkoka17** [zyphs21/HSCycleGalleryView#1]
hello
your video is very helpful, thanks a lot

but I could not manage to turn off  auto scrolling, I think it should be done by "willMove", but I could not do it, can you help me with example?

**Comment by zyphs21** [comment]
@dkoka17 Hello, I have pushed some code. 

Now the [autoScrollInterval](https://github.com/zyphs21/HSCycleGalleryView/blob/6ed558b1273414aebd99770670b04732c1873245/HSCycleGalleryView/Source/HSCycleGalleryView.swift#L25) is public. You can set `autoScrollInterval = 0` and it will not auto scroll.
